#!/usr/bin/env bash
# Change localhost and facebook.com resolution

cat << EOF > /etc/hosts
127.0.0.2 localhost
8.8.8.8 facebook.com

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF
