#!/usr/bin/env bash
# Configure localhost and facebook.com resolution

# Remove existing localhost entries
sed -i '/[[:space:]]localhost$/d' /etc/hosts

# Add new localhost entry
echo "127.0.0.2 localhost" >> /etc/hosts

# Remove existing facebook.com entries
sed -i '/[[:space:]]facebook.com$/d' /etc/hosts

# Add new facebook.com entry
echo "8.8.8.8 facebook.com" >> /etc/hosts
